"use client"
import { useState } from "react"
import { Plus } from "lucide-react"
import { PageHeader } from "@/components/dashboard/page-header"
import { InsightDialog } from "@/components/dashboard/insight-dialog"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
const base = [{ name: "Veg Thali", sold: 132, planned: 140, status: "On Track" }, { name: "Fried Rice", sold: 68, planned: 80, status: "Watch" }, { name: "Pav Bhaji", sold: 42, planned: 50, status: "High Demand" }, { name: "Sandwich", sold: 38, planned: 40, status: "On Track" }]
export default function SalesPage() { const [items, setItems] = useState(base), [open, setOpen] = useState(false), [insightOpen, setInsightOpen] = useState(false); return <><PageHeader title="Menu & Demand" description="Plan preparation quantities using current orders and historical demand."><Button variant="outline" onClick={() => setInsightOpen(true)}>Today</Button><Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button className="gap-2 bg-foreground text-background"><Plus className="size-4" />Add Menu Item</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Add menu item</DialogTitle></DialogHeader><form className="flex flex-col gap-4" onSubmit={(e) => { e.preventDefault(); const data = new FormData(e.currentTarget); setItems([...items, { name: String(data.get("name")), sold: 0, planned: Number(data.get("planned")), status: "On Track" }]); setOpen(false) }}><div><Label htmlFor="menu-name">Item name</Label><Input id="menu-name" name="name" required /></div><div><Label htmlFor="menu-planned">Planned quantity</Label><Input id="menu-planned" name="planned" type="number" required /></div><Button className="bg-foreground text-background">Save item</Button></form></DialogContent></Dialog></PageHeader><div className="mb-6 grid grid-cols-2 gap-4 lg:grid-cols-4">{[["Orders Received", "286"], ["Expected Final Demand", "324"], ["Meals Planned", "335"], ["Planning Gap", "+11"]].map(([label, value]) => <Card key={label}><CardContent className="p-5"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold">{value} {label === "Orders Received" ? "" : "meals"}</p></CardContent></Card>)}</div><Card><CardHeader><CardTitle className="text-base">Today&apos;s preparation plan</CardTitle></CardHeader><CardContent className="flex flex-col gap-5">{items.map((item) => <div key={item.name}><div className="mb-2 flex items-center justify-between text-sm"><span className="font-medium">{item.name}</span><span className="text-muted-foreground">{item.sold} sold / {item.planned} planned</span></div><div className="h-2 rounded-full bg-muted"><div className="h-2 rounded-full bg-[var(--color-positive)]" style={{ width: `${Math.min(100, item.sold / item.planned * 100)}%` }} /></div></div>)}</CardContent></Card><InsightDialog open={insightOpen} onOpenChange={setInsightOpen} title="Today&apos;s menu & demand" description="See rush windows and estimated versus actual demand before preparing the next batch." /></> }
