"use client"

import { useEffect, useState } from "react"
import { Calendar, Download, ClipboardList, IndianRupee, Utensils, Trash2 } from "lucide-react"
import { InsightDialog } from "@/components/dashboard/insight-dialog"
import { PageHeader } from "@/components/dashboard/page-header"
import { MetricCard } from "@/components/dashboard/metric-card"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, LineChart, Line, PieChart, Pie, Cell } from "recharts"

const demand = [{day:"Mon", demand:310, prepared:340},{day:"Tue",demand:328,prepared:345},{day:"Wed",demand:285,prepared:330},{day:"Thu",demand:341,prepared:350},{day:"Fri",demand:319,prepared:335},{day:"Sat",demand:244,prepared:260},{day:"Sun",demand:198,prepared:215}]
const waste = [{day:"Mon",kg:2.1},{day:"Tue",kg:1.8},{day:"Wed",kg:2.4},{day:"Thu",kg:1.7},{day:"Fri",kg:1.9},{day:"Sat",kg:1.4},{day:"Sun",kg:1.1}]
const breakdown = [{name:"Rice",value:34,color:"#9fbe91"},{name:"Vegetables",value:26,color:"#c7d9bd"},{name:"Roti/Bread",value:18,color:"#4b5563"},{name:"Curries",value:14,color:"#9ca3af"},{name:"Other",value:8,color:"#d1d5db"}]

export default function DashboardPage() {
 const [wasteTotal,setWasteTotal]=useState(12.4)
 const [insightOpen,setInsightOpen]=useState(false)
 useEffect(()=>{const saved=window.localStorage.getItem("canteenwise-waste-total"); if(saved) setWasteTotal(Number(saved))},[])
 return <><PageHeader title="Good morning, Canteen Team" description="Here's today's demand, preparation and canteen performance."><Button variant="outline" className="gap-2 bg-transparent" onClick={()=>setInsightOpen(true)}><Calendar className="w-4 h-4"/>Today</Button><Button variant="outline" className="gap-2 bg-transparent"><Download className="w-4 h-4"/>Export Report</Button></PageHeader>
 <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-6"><MetricCard title="Orders Today" value="286" change="+6.4% vs last Tuesday" isPositiveOutcome icon={ClipboardList}/><MetricCard title="Revenue Today" value="₹18,460" change="+5.8% vs last Tuesday" isPositiveOutcome icon={IndianRupee}/><MetricCard title="Meals Prepared" value="335" change="92% currently served/planned" isPositiveOutcome icon={Utensils}/><MetricCard title="Estimated Surplus" value="14 meals" change="↓21% vs last week" isPositiveOutcome icon={Trash2}/></div>
 <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 mb-6"><Card className="lg:col-span-2"><CardHeader><CardTitle className="text-base">Demand vs Preparation</CardTitle><p className="text-sm text-muted-foreground">Compare actual meal demand with prepared quantities.</p></CardHeader><CardContent><div className="h-[260px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={demand}><CartesianGrid vertical={false} stroke="#e5e5e5"/><XAxis dataKey="day" tickLine={false} axisLine={false}/><YAxis tickLine={false} axisLine={false}/><Tooltip/><Bar dataKey="demand" name="Actual Demand" fill="#3d3d3d" radius={[4,4,0,0]}/><Bar dataKey="prepared" name="Meals Prepared" fill="#b4d4a5" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div></CardContent></Card><Card><CardHeader><CardTitle className="text-base">Today's Menu</CardTitle></CardHeader><CardContent className="space-y-5">{[["Veg Thali","124 sold • 140 planned","On Track"],["Fried Rice","73 sold • 80 planned","High Demand"],["Pav Bhaji","46 sold • 50 planned","On Track"],["Sandwich","31 sold • 40 planned","Possible Surplus"]].map(([name,meta,status])=><div key={name} className="flex items-center justify-between"><div><p className="text-sm font-medium">{name}</p><p className="text-xs text-muted-foreground mt-1">{meta}</p></div><span className={`text-xs ${status === "Possible Surplus" ? "text-amber-700" : "text-[var(--color-positive)]"}`}>{status}</span></div>)}</CardContent></Card></div>
 <div className="grid grid-cols-1 lg:grid-cols-3 gap-4"><Card><CardHeader><CardTitle className="text-base">Weekly Food Waste</CardTitle></CardHeader><CardContent><p className="text-3xl font-semibold">{wasteTotal.toFixed(1)} kg</p><p className="text-xs text-[var(--color-positive)] mt-1">↓17.3% vs last week</p><div className="h-[120px] mt-4"><ResponsiveContainer width="100%" height="100%"><LineChart data={waste}><XAxis dataKey="day" hide/><YAxis hide/><Line type="monotone" dataKey="kg" stroke="#86a878" strokeWidth={2} dot={false}/></LineChart></ResponsiveContainer></div></CardContent></Card><Card className="lg:col-span-2"><CardHeader><CardTitle className="text-base">Waste Breakdown</CardTitle></CardHeader><CardContent className="flex flex-col sm:flex-row items-center gap-6"><div className="h-[170px] w-[190px]"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={breakdown} innerRadius={50} outerRadius={75} dataKey="value" paddingAngle={2}>{breakdown.map((item)=><Cell key={item.name} fill={item.color}/>)}</Pie></PieChart></ResponsiveContainer></div><div className="grid grid-cols-2 gap-x-8 gap-y-3 flex-1">{breakdown.map((item)=><div key={item.name} className="flex items-center gap-2 text-sm"><i className="w-2 h-2 rounded-full" style={{backgroundColor:item.color}}/>{item.name}<b className="ml-auto">{item.value}%</b></div>)}<div className="col-span-2 border-t pt-3 mt-1 text-sm"><span className="text-muted-foreground">Estimated cost lost:</span> <b>₹1,860</b><br/><span className="text-muted-foreground">Waste avoided vs baseline:</span> <b>8.6 kg</b></div></div></CardContent></Card></div><InsightDialog open={insightOpen} onOpenChange={setInsightOpen} title="Today at a glance" description="Hourly demand, rush intensity, preparation accuracy and waste signals." /></>
}
